"""

When changed models, update using:
     $ python manage.py db init
     $ python manage.py db migrate
     $ python manage.py db upgrade

"""

from sqlalchemy import Column, Integer, String, Date, Float, Table
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
import textwrap
from datetime import datetime

from sqlalchemy.ext.declarative import declarative_base

import datetime, json

Base = declarative_base()

def pretty_print(mystr):
    lines = ""
    for line in textwrap.wrap(mystr):
        lines += line + "\n"
    return lines.strip()

class Title_Comparison(Base):
    __tablename__ = "title_comparison"
    id1 = Column(String(255), primary_key=True)
    id2 = Column(String(255))
    normal_display = Column(String(4000)) 
    lower_display = Column(String(4000)) 
    sources_display = Column(String(2000))
    title1 = Column(String(255))
    title2 = Column(String(255))
    source1 = Column(String(255))
    source2 = Column(String(255))
    title1_date = Column(Date)
    title2_date = Column(Date)
    harmvirtue_title = Column(Float)
    harmvice_title = Column(Float)
    fairnessvirtue_title = Column(Float)
    fairnessvice_title = Column(Float)
    ingroupvirtue_title = Column(Float)
    ingroupvice_title = Column(Float)
    authorityvirtue_title = Column(Float)
    authorityvice_title = Column(Float)
    purityvirtue_title = Column(Float)
    purityvice_title = Column(Float)
    moralitygeneral_title = Column(Float)
    bias_count_title = Column(Float)
    assertives_count_title = Column(Float)
    factives_count_title = Column(Float)
    hedges_count_title = Column(Float)
    implicatives_count_title = Column(Float)
    report_verbs_count_title = Column(Float)
    positive_op_count_title = Column(Float)
    negative_op_count_title = Column(Float)
    wneg_count_title = Column(Float)
    wpos_count_title = Column(Float)
    wneu_count_title = Column(Float)
    sneg_count_title = Column(Float)
    spos_count_title = Column(Float)
    sneu_count_title = Column(Float)
    ttr_title = Column(Float)
    vad_neg_title = Column(Float)
    vad_neu_title = Column(Float)
    vad_pos_title = Column(Float)
    fke_title = Column(Float)
    smog_title = Column(Float)
    stop_title = Column(Float)
    wordlen_title = Column(Float)
    wc_title = Column(Float)
    nb_pobj_title = Column(Float)
    nb_psubj_title = Column(Float)
    quotes_title = Column(Float)
    exclaim_title = Column(Float)
    allpunc_title = Column(Float)
    allcaps_title = Column(Float)
    cc_title = Column(Float)
    cd_title = Column(Float)
    dt_title = Column(Float)
    ex_title = Column(Float)
    fw_title = Column(Float)
    in_pos_title = Column(Float)
    jj_title = Column(Float)
    jjr_title = Column(Float)
    jjs_title = Column(Float)
    ls_title = Column(Float)
    md_title = Column(Float)
    nn_title = Column(Float)
    nns_title = Column(Float)
    nnp_title = Column(Float)
    nnps_title = Column(Float)
    pdt_title = Column(Float)
    pos_title = Column(Float)
    prp_title = Column(Float)
    prp1_title = Column(Float) #renamed from PRP$
    rb_title = Column(Float)
    rbr_title = Column(Float)
    rbs_title = Column(Float)
    rp_title = Column(Float)
    sym_title = Column(Float)
    to_pos_title = Column(Float)
    uh_title = Column(Float)
    wp1_title = Column(Float) #renamed from WP$
    wrb_title = Column(Float)
    vb_title = Column(Float)
    vbd_title = Column(Float)
    vbg_title = Column(Float)
    vbn_title = Column(Float)
    vbp_title = Column(Float)
    vbz_title = Column(Float)
    wdt_title = Column(Float)
    wp_title = Column(Float)
    ingest_title = Column(Float)
    cause_title = Column(Float)
    insight_title = Column(Float)
    cogmech_title = Column(Float)
    sad_title = Column(Float)
    inhib_title = Column(Float)
    certain_title = Column(Float)
    tentat_title = Column(Float)
    discrep_title = Column(Float)
    space_title = Column(Float)
    time_title = Column(Float)
    excl_title = Column(Float)
    incl_title = Column(Float)
    relativ_title = Column(Float)
    motion_title = Column(Float)
    quant_title = Column(Float)
    numbers_title = Column(Float)
    swear_title = Column(Float)
    funct_title = Column(Float)
    ppron_title = Column(Float)
    pronoun_title = Column(Float)
    we_title = Column(Float)
    i_title = Column(Float)
    shehe_title = Column(Float)
    you_title = Column(Float)
    ipron_title = Column(Float)
    they_title = Column(Float)
    death_title = Column(Float)
    bio_title = Column(Float)
    body_title = Column(Float)
    hear_title = Column(Float)
    feel_title = Column(Float)
    percept_title = Column(Float)
    see_title = Column(Float)
    filler_title = Column(Float)
    health_title = Column(Float)
    sexual_title = Column(Float)
    social_title = Column(Float)
    family_title = Column(Float)
    friend_title = Column(Float)
    humans_title = Column(Float)
    affect_title = Column(Float)
    posemo_title = Column(Float)
    negemo_title = Column(Float)
    anx_title = Column(Float)
    anger_title = Column(Float)
    assent_title = Column(Float)
    nonfl_title = Column(Float)
    verb_title = Column(Float)
    article_title = Column(Float)
    past_title = Column(Float)
    auxverb_title = Column(Float)
    future_title = Column(Float)
    present_title = Column(Float)
    preps_title = Column(Float)
    adverb_title = Column(Float)
    negate_title = Column(Float)
    conj_title = Column(Float)
    home_title = Column(Float)
    leisure_title = Column(Float)
    achieve_title = Column(Float)
    work_title = Column(Float)
    relig_title = Column(Float)
    money_title = Column(Float)  